#!/bin/bash

# shellcheck source=.settings
. "${BASH_SOURCE%/*}/.settings"

tmux start-server
tmux new-session -d -s "$PROJECT"

tmux split-window -v -l '90%'
tmux select-pane -t 0
tmux split-window -h -l '50%'

tmux select-pane -t 0
tmux send-keys "npx livereload \"$DOCS_DIR\" --wait 250" C-m

tmux select-pane -t 1
tmux send-keys "python3 -m http.server --directory \"$DOCS_DIR\"" C-m

tmux select-pane -t 2
tmux send-keys "dune build @doc @check @runtest -w" C-m

tmux attach-session -t "$PROJECT"
